<%@ Page Title="" Language="C#" MasterPageFile="~/munshi.Master" AutoEventWireup="true" CodeBehind="Manage_Goods.aspx.cs" Inherits="hostel________.munsi.Manage_Goods" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
 <br />
    <asp:Repeater ID="RepDetails" runat="server">
        <ItemTemplate>
            <p>
                You have only 
                <asp:Label ID="Label1" runat="server" Text='<%#Eval("Quantity") %>'></asp:Label> -
                <asp:Label ID="Label2" runat="server" Text='<%#Eval("Unit") %>'></asp:Label>
                 &nbsp;<asp:Label ID="Label3" runat="server" Text='<%#Eval("Goods_Name") %>'></asp:Label>
                 in the stock.
             </p>
        </ItemTemplate>
    </asp:Repeater>
    
    <br />
<div class="grid"
                style = "overflow-x:scroll">

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" 
        CellPadding="4" CellSpacing="2" DataKeyNames="Sr_No" 
        DataSourceID="SqlDataSource1" ForeColor="Black" Width="100%">
        <Columns>
            <asp:BoundField DataField="Sr_No" HeaderText="Sr_No" InsertVisible="False" 
                ReadOnly="True" SortExpression="Sr_No" />
            <asp:BoundField DataField="Goods_Name" HeaderText="Goods_Name" 
                SortExpression="Goods_Name" />
            <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" 
                SortExpression="Quantity" />
            <asp:BoundField DataField="Unit" HeaderText="Unit" SortExpression="Unit" />
            <asp:BoundField DataField="Expairy_Date" HeaderText="Expairy_Date" 
                SortExpression="Expairy_Date" />
            <asp:BoundField DataField="Updated_On" HeaderText="Updated_On" 
                SortExpression="Updated_On" />
            <asp:BoundField DataField="Munshi" HeaderText="Munshi" 
                SortExpression="Munshi" />
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hRegistrationConnectionString %>" 
        SelectCommand="SELECT * FROM [Goods_Data]" UpdateCommand="Update [Goods_Data] set [Goods_Name]=@Goods_Name, [Type]=@Type, [Quantity]=@Quantity, [Unit]=@Unit, [Expairy_Date]=@Expairy_Date, [Updated_On]=@Updated_On where [Sr_No]=@Sr_No" 
        DeleteCommand ="DELETE FROM [Goods_Data] WHERE [Sr_No]=@Sr_No">
        
        </asp:SqlDataSource>

</div>

</asp:Content>
